### ISSUE TITLE
ConsumerGroup not claiming partitions on repeated creation

### ISSUE THREAD

**Issue by bartek-75** [bsm/sarama#1]
I am creating ConsumerGroup then calling Claim, then closing it and creating again.
Each next creation claims less partition till no partitions at all. Here is the code:

```
import (
    "fmt"
    "github.com/Shopify/sarama"
    "github.com/bsm/sarama/cluster"
    "os"
    "time"
)

func main(){
for j := 0; j < 10; j++ {
    var err error
    var consumerConfig = &sarama.ConsumerConfig{MaxWaitTime: time.Duration(250 * time.Millisecond), EventBufferSize: 5, OffsetMethod: sarama.OffsetMethodNewest}
    var clientConfig = &sarama.ClientConfig{MetadataRetries: 30, WaitForElection: time.Second}

    client, err := sarama.NewClient("test_id", []string{"172.16.4.33:9092"}, clientConfig)
    if err != nil {
        os.Exit(1)
    }

    zk, err := cluster.NewZK([]string{"172.16.4.33:2181"}, time.Duration(30*time.Second))
    if err != nil {
        client.Close()
        os.Exit(1)
    }

    consumer, err := cluster.NewConsumerGroup(client, zk, "test_id", "test_topic", nil, consumerConfig)
    if err != nil {
        client.Close()
        os.Exit(1)
    }
    for i := 0; i < 10; i++ {
        fmt.Println("Group claims ", consumer.Claims())
        time.Sleep(1 * time.Second)
    }
    consumer.Close()
    client.Close()
    time.Sleep(10 * time.Second)
    }
}
```

And the output:
    Group claims  []
    Group claims  [2]
    Group claims  [2 0]
    Group claims  [2 0 3 1]
    Group claims  [2 0 3 1 4] -- all partitions (OK)
......
Second run:
    Group claims  []
    Group claims  [1]
    Group claims  [1 4]
    Group claims  [1 4] -- missing partitions
.......
next run:
    Group claims  []
    Group claims  [4]
    Group claims  [4]
    Group claims  [4]
.........
next:
    Group claims  []
    Group claims  []
    Group claims  []
    Group claims  []

What am i doing wrong?

**Comment by dim** [comment]
The latest sarama version is reusing cached broker objects, will push a fix

**Comment by dim** [comment]
Fixed in https://github.com/bsm/sarama/commit/fc0d052
